"""What can be run, what it costs, and how to invoke it. Pure data.

No I/O, no Qt, no network — so it imports without a display and the tests can
check every entry offline.

**A model here is a *recipe*, not a file.** local-upscaler's models were a
`.param`/`.bin` pair of a few megabytes; one entry here is a diffusion
transformer, a text encoder that is itself a 4-8 B language model, a VAE, and
sometimes a vision projector or an adapter — four files and 5-35 GB. Nothing is
bundled: a recipe downloads on demand the first time it is chosen, exactly as
the upscaler's models do, so a checkout stays small and the user pays only for
the tiers they use.

**Every `size` is an exact byte count**, and `fetch` refuses a file that arrives
any other length. This is not belt-and-braces: a captive portal, a rate limit or
a moved URL all return HTTP 200 with an HTML body, and writing that to
`flux-2-klein-4b-Q4_0.gguf` produces a file that fails minutes later inside ggml
with an unreadable error. The counts are machine-generated by `--refresh-sizes`
rather than typed, because a wrong one makes a recipe permanently
un-downloadable and no offline test can catch it.

**The ladder deliberately extends past what the development machine can run.**
It is a GTX 1050 Ti with 3.2 GiB of usable VRAM; `flux2-dev-q4` wants roughly
ten times that. Those rows are not dead weight — `hardware.verdict` grades every
recipe against the machine it is actually on and the UI says which is which, so
the same catalog describes this box today and a larger one later without an
edit here.

`sec_per_mpx_step` and `working_gb` are **priors**, and the honest ones are the
measured figures `settings.Calibration` accumulates after the first run of each
recipe. See `runner.throughput`.
"""

from __future__ import annotations

from dataclasses import dataclass

#: How a recipe is executed. The server keeps multi-gigabyte weights resident
#: between edits, which is the difference between iterating on a prompt and
#: waiting out a fresh model load every time. It is the default. The CLI path
#: exists for recipes whose inputs the server's JSON API cannot express —
#: PhotoMaker takes `--pm-id-images-dir`, a *directory path* that is fixed when
#: the server starts, so a face set cannot be chosen per request.
ENGINE_SERVER = "server"
ENGINE_CLI = "cli"

#: `File.role` -> the sd.cpp flag that points at it. Verified against
#: `sd-cli --help` at commit 7f410a3 rather than read out of the docs, which lag
#: the binary (`--clip-on-cpu` is documented but deprecated in favour of
#: `--backend te=cpu`, and `--llm_vision` takes an underscore where almost every
#: other flag takes a dash).
ROLE_FLAGS = {
    "checkpoint": "-m",                    # a full SD1.x/SDXL checkpoint
    "diffusion": "--diffusion-model",      # a standalone DiT/UNet
    "llm": "--llm",
    "llm_vision": "--llm_vision",
    "t5xxl": "--t5xxl",
    "clip_l": "--clip_l",
    "clip_g": "--clip_g",
    "clip_vision": "--clip_vision",
    "vae": "--vae",
    "ip_adapter": "--ip-adapter",
    "photo_maker": "--photo-maker",
}

#: Where each role is filed under the models directory. Mirrors ComfyUI's
#: layout so a user who already has these files can symlink a tree in, and so
#: two repos' `model.safetensors` cannot collide.
ROLE_DIRS = {
    "checkpoint": "checkpoints",
    "diffusion": "diffusion",
    "llm": "text_encoders",
    "llm_vision": "text_encoders",
    "t5xxl": "text_encoders",
    "clip_l": "text_encoders",
    "clip_g": "text_encoders",
    "clip_vision": "clip_vision",
    "vae": "vae",
    "ip_adapter": "ip_adapter",
    "photo_maker": "photomaker",
}

HF = "https://huggingface.co"


@dataclass(frozen=True)
class File:
    """One weight file a recipe needs."""

    role: str
    repo: str
    #: Path within the HuggingFace repo.
    path: str
    #: Exact size in bytes. Verified after download; see the module docstring.
    size: int
    #: Local filename. Defaults to the repo path's basename, which is unique
    #: across this catalog; set it only when two repos ship the same basename.
    name: str = ""

    def filename(self) -> str:
        return self.name or self.path.rsplit("/", 1)[-1]

    def subdir(self) -> str:
        return ROLE_DIRS[self.role]

    def url(self) -> str:
        return f"{HF}/{self.repo}/resolve/main/{self.path}"

    def flag(self) -> str:
        return ROLE_FLAGS[self.role]


@dataclass(frozen=True)
class Recipe:
    """One selectable model, and everything needed to run it."""

    id: str
    label: str
    #: Groups recipes that share prompt conventions and reference handling.
    family: str
    blurb: str
    author: str
    licence: str
    url: str
    files: tuple[File, ...]

    # -- how to sample ---------------------------------------------------
    steps: int
    cfg_scale: float
    sampling_method: str = "euler"
    scheduler: str = ""                 # "" means the model's own default
    #: Distilled guidance, for models with a guidance input (Kontext).
    guidance: float | None = None
    flow_shift: float | None = None
    #: Denoise strength when an init image is supplied to a non-edit model.
    strength: float = 0.75
    #: Flags that are always right for this recipe.
    extra_args: tuple[str, ...] = ()
    engine: str = ENGINE_SERVER

    # -- references ------------------------------------------------------
    #: How many reference images the model meaningfully uses. 0 means it takes
    #: none; 1 means one; more means true multi-reference composition.
    max_refs: int = 1
    #: True when references go through `--ref-image`; False when they go
    #: through the single `--ip-adapter-image`, or through PhotoMaker's
    #: id-images directory.
    ref_images: bool = True
    #: How the image being edited reaches the model, and the two families here
    #: differ fundamentally.
    #:
    #: An *edit* model — Kontext, FLUX.2, Qwen-Image-Edit — was trained to see
    #: the image as reference **1** and to read the prompt as an instruction
    #: about it. There is no denoising strength; the model decides what to keep.
    #:
    #: A *generative* model — SD1.5, SDXL — has no such notion. It takes the
    #: image as `--init-img` and partially re-noises it, and `strength` decides
    #: how much of the original survives.
    #:
    #: Getting this backwards is quiet rather than loud: passing an edit model
    #: an init image produces a plausible picture that ignores the instruction,
    #: which looks like a bad model rather than a wiring mistake.
    source_as_ref: bool = True

    # -- shape -----------------------------------------------------------
    default_size: int = 1024
    #: Multiple that width and height are rounded to. Latent patching means an
    #: off-grid size is silently rounded by the engine, which then returns an
    #: image that is not the size the UI promised.
    size_multiple: int = 64

    # -- hardware cost (priors; measurement replaces the timing one) ------
    #: VRAM needed *beyond* the weights at one megapixel — activations,
    #: attention and the sampler's buffers — on a card with usable fp16.
    #: Scaled by `hardware.WORK_EXPONENT`, not linearly, and doubled for a
    #: card without fp16 (every Pascal GPU under Vulkan).
    #:
    #: `flux2-klein-4b-q4` is anchored on sd.cpp's own reported peak compute
    #: buffer; the rest are scaled from it by hidden size.
    working_gb: float = 1.0
    #: Seconds for one sampling step at one megapixel, with no references and
    #: weights resident in VRAM. Scaled by `runner.PIXEL_EXPONENT` rather than
    #: linearly, because attention is quadratic in tokens.
    #:
    #: `flux2-klein-4b-q4` is anchored on a real measurement — 22.3 s/step at
    #: 512x512 on a GTX 1050 Ti under Vulkan. The rest are scaled from it by
    #: parameter count and are honest guesses until `--bench` replaces them.
    sec_per_mpx_step: float = 10.0
    #: Fixed cost of loading the weights and warming the backend.
    load_s: float = 30.0

    # -- derived ---------------------------------------------------------
    def weights_bytes(self) -> int:
        """Total download, and the working set the weights themselves occupy."""
        return sum(f.size for f in self.files)

    def weights_gb(self) -> float:
        return self.weights_bytes() / 1e9

    def file(self, role: str) -> File | None:
        return next((f for f in self.files if f.role == role), None)

    def has(self, role: str) -> bool:
        return self.file(role) is not None

    def uses_photomaker(self) -> bool:
        return self.has("photo_maker")

    def uses_ip_adapter(self) -> bool:
        return self.has("ip_adapter")


# --------------------------------------------------------------- shared files
# Named once because several recipes share them, so a size correction lands in
# one place and the fetcher naturally deduplicates the download.
_FLUX2_VAE = File("vae", "Comfy-Org/flux2-klein",
                  "split_files/vae/flux2-vae.safetensors", 336_211_292)
_FLUX1_AE = File("vae", "black-forest-labs/FLUX.1-schnell",
                 "ae.safetensors", 335_304_388, name="flux1-ae.safetensors")
_CLIP_L = File("clip_l", "comfyanonymous/flux_text_encoders",
               "clip_l.safetensors", 246_144_152)
_QWEN_IMAGE_VAE = File("vae", "Comfy-Org/Qwen-Image_ComfyUI",
                       "split_files/vae/qwen_image_vae.safetensors", 253_806_246)
_CLIP_VISION_H = File("clip_vision", "Comfy-Org/Wan_2.1_ComfyUI_repackaged",
                      "split_files/clip_vision/clip_vision_h.safetensors",
                      1_264_219_396)

_BFL_NC = "FLUX.1 [dev] Non-Commercial License"

RECIPES: tuple[Recipe, ...] = (
    # ---------------------------------------------------------------- tiny
    Recipe(
        id="sd15-ip",
        label="Stable Diffusion 1.5 + IP-Adapter",
        family="sd15",
        blurb="Seconds per image, and the only tier that is genuinely fast here. "
              "Good at 'make it look like this'; it is not an instruction editor, "
              "so 'make them ride a motorcycle' will disappoint.",
        author="Robin Rombach et al.; IP-Adapter by Hu Ye et al.",
        licence="CreativeML OpenRAIL-M / Apache-2.0",
        url="https://huggingface.co/h94/IP-Adapter",
        files=(
            File("checkpoint", "Comfy-Org/stable-diffusion-v1-5-archive",
                 "v1-5-pruned-emaonly-fp16.safetensors", 2_132_696_762),
            File("ip_adapter", "h94/IP-Adapter",
                 "models/ip-adapter-plus-face_sd15.safetensors", 98_183_288),
            _CLIP_VISION_H,
        ),
        steps=24, cfg_scale=7.0, sampling_method="dpm++2m", scheduler="karras",
        strength=0.65,
        # One `--ip-adapter-image`, and no `--ref-image` support at all.
        max_refs=1, ref_images=False,
        source_as_ref=False,
        default_size=512, size_multiple=64,
        working_gb=0.55, sec_per_mpx_step=2.5, load_s=12.0,
    ),

    # ---------------------------------------------------- the default tier
    Recipe(
        id="flux2-klein-4b-q4",
        label="FLUX.2 Klein 4B (Q4)",
        family="flux2",
        blurb="Four sampling steps, and small enough to sit entirely in 4 GB of "
              "VRAM. Understands several reference images at once, which is what "
              "makes 'this face, that jacket, that street' work.",
        author="Black Forest Labs",
        licence="Apache-2.0",
        url="https://huggingface.co/black-forest-labs/FLUX.2-klein-4B",
        files=(
            File("diffusion", "leejet/FLUX.2-klein-4B-GGUF",
                 "flux-2-klein-4b-Q4_0.gguf", 2_460_378_560),
            File("llm", "Qwen/Qwen3-4B-GGUF",
                 "Qwen3-4B-Q4_K_M.gguf", 2_497_280_256),
            _FLUX2_VAE,
        ),
        steps=4, cfg_scale=1.0, sampling_method="euler",
        max_refs=6,
        working_gb=1.3, sec_per_mpx_step=69.0, load_s=25.0,
    ),
    Recipe(
        id="flux2-klein-4b-q8",
        label="FLUX.2 Klein 4B (Q8)",
        family="flux2",
        blurb="The same model at a quantisation that gives up almost nothing. "
              "Nearly twice the weights, so on a 4 GB card it runs out of RAM "
              "rather than VRAM.",
        author="Black Forest Labs",
        licence="Apache-2.0",
        url="https://huggingface.co/black-forest-labs/FLUX.2-klein-4B",
        files=(
            File("diffusion", "leejet/FLUX.2-klein-4B-GGUF",
                 "flux-2-klein-4b-Q8_0.gguf", 4_300_629_440),
            File("llm", "Qwen/Qwen3-4B-GGUF",
                 "Qwen3-4B-Q8_0.gguf", 4_280_404_704),
            _FLUX2_VAE,
        ),
        steps=4, cfg_scale=1.0, sampling_method="euler",
        max_refs=6,
        working_gb=1.3, sec_per_mpx_step=76.0, load_s=35.0,
    ),

    # ------------------------------------------------------- quality tier
    Recipe(
        id="kontext-q3",
        label="FLUX.1 Kontext dev (Q3)",
        family="kontext",
        blurb="The instruction editor everything else is measured against. It "
              "follows 'make this scenery rainy' better than anything else that "
              "fits on consumer hardware — at six times the steps and three "
              "times the weights of Klein.",
        author="Black Forest Labs",
        licence=_BFL_NC,
        url="https://huggingface.co/black-forest-labs/FLUX.1-Kontext-dev",
        files=(
            File("diffusion", "QuantStack/FLUX.1-Kontext-dev-GGUF",
                 "flux1-kontext-dev-Q3_K_S.gguf", 5_225_604_384),
            File("t5xxl", "city96/t5-v1_1-xxl-encoder-gguf",
                 "t5-v1_1-xxl-encoder-Q3_K_M.gguf", 2_296_075_456),
            _CLIP_L,
            _FLUX1_AE,
        ),
        steps=24, cfg_scale=1.0, guidance=2.5, sampling_method="euler",
        # Kontext was trained on one reference. sd.cpp will pass more, and with
        # `--increase-ref-index` they are addressable as image 2 and 3, but
        # quality falls off fast — hence 3 rather than Klein's 6.
        max_refs=3,
        working_gb=1.7, sec_per_mpx_step=195.0, load_s=60.0,
    ),
    Recipe(
        id="sdxl-photomaker",
        label="SDXL + PhotoMaker v2 (faces)",
        family="photomaker",
        blurb="Identity from several photos of the same person, which is a "
              "different trick from copying one reference: give it three or four "
              "shots of a face and it generalises rather than pasting. SDXL only.",
        author="TencentARC; SDXL by Stability AI",
        licence="Apache-2.0 / CreativeML Open RAIL++-M",
        url="https://huggingface.co/TencentARC/PhotoMaker-V2",
        files=(
            File("checkpoint", "stabilityai/stable-diffusion-xl-base-1.0",
                 "sd_xl_base_1.0.safetensors", 6_938_078_334),
            File("photo_maker", "bssrdf/PhotoMakerV2",
                 "photomaker-v2.safetensors", 1_799_451_104),
            File("vae", "madebyollin/sdxl-vae-fp16-fix",
                 "sdxl_vae.safetensors", 334_641_162),
        ),
        steps=30, cfg_scale=5.0, sampling_method="euler_a",
        # `--pm-id-images-dir` is a directory of faces, not a `--ref-image`
        # list, and it is a startup flag the server API cannot set per request.
        engine=ENGINE_CLI, max_refs=4, ref_images=False,
        source_as_ref=False,
        working_gb=1.2, sec_per_mpx_step=54.0, load_s=45.0,
    ),
    Recipe(
        id="flux2-klein-9b-q4",
        label="FLUX.2 Klein 9B (Q4)",
        family="flux2",
        blurb="Klein's larger sibling: the same four steps and the same "
              "multi-reference behaviour, with markedly better prompt adherence. "
              "Wants a 12 GB card to be comfortable.",
        author="Black Forest Labs",
        licence="Apache-2.0",
        url="https://huggingface.co/black-forest-labs/FLUX.2-klein-9B",
        files=(
            File("diffusion", "leejet/FLUX.2-klein-9B-GGUF",
                 "flux-2-klein-9b-Q4_0.gguf", 5_616_208_032),
            File("llm", "Qwen/Qwen3-8B-GGUF",
                 "Qwen3-8B-Q4_K_M.gguf", 5_027_783_488),
            _FLUX2_VAE,
        ),
        steps=4, cfg_scale=1.0, sampling_method="euler",
        max_refs=6,
        working_gb=1.9, sec_per_mpx_step=153.0, load_s=60.0,
    ),

    # ------------------------------------------------------- the heavy end
    Recipe(
        id="qwen-edit-2509-q2",
        label="Qwen-Image-Edit 2509 (Q2)",
        family="qwen-edit",
        blurb="Trained for exactly this job: a person from one picture, a "
              "garment from another, a place from a third. The best multi-image "
              "compositor here, and by a distance the slowest — its text encoder "
              "is a 7 B vision-language model in its own right.",
        author="Qwen team, Alibaba",
        licence="Apache-2.0",
        url="https://huggingface.co/Qwen/Qwen-Image-Edit-2509",
        files=(
            File("diffusion", "QuantStack/Qwen-Image-Edit-2509-GGUF",
                 "Qwen-Image-Edit-2509-Q2_K.gguf", 7_147_452_960),
            File("llm", "unsloth/Qwen2.5-VL-7B-Instruct-GGUF",
                 "Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf", 4_683_072_384),
            File("llm_vision", "unsloth/Qwen2.5-VL-7B-Instruct-GGUF",
                 "mmproj-F16.gguf", 1_354_163_040,
                 name="Qwen2.5-VL-7B-Instruct-mmproj-F16.gguf"),
            _QWEN_IMAGE_VAE,
        ),
        steps=20, cfg_scale=2.5, sampling_method="euler", flow_shift=3.0,
        #: Upstream says quality is best with one to three images.
        max_refs=3,
        working_gb=2.3, sec_per_mpx_step=540.0, load_s=120.0,
    ),
    Recipe(
        id="flux2-dev-q4",
        label="FLUX.2 dev (Q4)",
        family="flux2",
        blurb="The ceiling of this catalog, and a deliberate one: 34 GB of "
              "weights behind a 24 B language model. Listed so a new machine has "
              "something to fail to be enough for.",
        author="Black Forest Labs",
        licence="FLUX.2 [dev] Non-Commercial License",
        url="https://huggingface.co/black-forest-labs/FLUX.2-dev",
        files=(
            File("diffusion", "unsloth/FLUX.2-dev-GGUF",
                 "flux2-dev-Q4_K_S.gguf", 19_789_861_856),
            File("llm", "unsloth/Mistral-Small-3.2-24B-Instruct-2506-GGUF",
                 "Mistral-Small-3.2-24B-Instruct-2506-Q4_K_M.gguf",
                 14_333_922_848),
            _FLUX2_VAE,
        ),
        steps=28, cfg_scale=1.0, sampling_method="euler",
        max_refs=6,
        working_gb=3.2, sec_per_mpx_step=770.0, load_s=240.0,
    ),
)

DEFAULT_RECIPE_ID = "flux2-klein-4b-q4"

_BY_ID = {r.id: r for r in RECIPES}


def get(recipe_id: str) -> Recipe:
    """A recipe by id, falling back to the default.

    Falls back rather than raising so a settings file naming a recipe this
    version dropped opens the app instead of crashing it on the first read.
    """
    return _BY_ID.get(recipe_id) or _BY_ID[DEFAULT_RECIPE_ID]


def exists(recipe_id: str) -> bool:
    return recipe_id in _BY_ID


def ids() -> tuple[str, ...]:
    return tuple(r.id for r in RECIPES)


def all_files() -> tuple[File, ...]:
    """Every distinct file in the catalog, deduplicated by local filename."""
    seen: dict[str, File] = {}
    for recipe in RECIPES:
        for f in recipe.files:
            seen.setdefault(f.filename(), f)
    return tuple(seen.values())
